org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)
forge_version=40.2.21
forge_version_range=[40,)
loader_version_range=[40,)

mapping_channel=official
mapping_version=1.18.2

## Mod Properties

mod_id=knightmod
mod_name=Knight Mod
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.knightmod
mod_authors=KnightMod
mod_description=Adds a full knight armor set, a knight sword, and a knight dagger.
